-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "priority" SET DEFAULT 'LOW',
ALTER COLUMN "category" SET DEFAULT 'TODO',
ALTER COLUMN "dueAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER',
ALTER COLUMN "refreshToken" DROP NOT NULL;
